### Load SQL Magics

In [1]:
%load_ext sql

### Load sqlalchemy to create a local environment of PostgreSQL server

In [2]:
from sqlalchemy import create_engine
import pandas as pd

In [3]:
# %sql dialect+driver://username:password@host:port/database
%sql postgresql://jovyan:postgres@localhost:8765/rsm-docker

'Connected: jovyan@rsm-docker'

### Create engine

In [4]:
engine = create_engine("postgresql://jovyan:postgres@localhost:8765/rsm-docker")

In [5]:
engine

Engine(postgresql://jovyan:***@localhost:8765/rsm-docker)

### Get files as data frames

In [6]:
accounts = pd.read_excel("data/accounts.xlsx")
orders = pd.read_excel("data/orders.xlsx")
region = pd.read_excel("data/region.xlsx")
sales_reps = pd.read_excel("data/sales_reps.xlsx")
web_events = pd.read_excel("data/web_events.xlsx")

### Data ingestion to tables in a database (here - rsm-docker)

In [7]:
accounts.to_sql("accounts", engine, if_exists="replace")
orders.to_sql("orders", engine, if_exists="replace")
region.to_sql("region", engine, if_exists="replace")
sales_reps.to_sql("sales_reps", engine, if_exists="replace")
web_events.to_sql("web_events", engine, if_exists="replace")

73

In [8]:
engine.table_names()

/tmp/ipykernel_357/4162273999.py:1: SADeprecationWarning: The Engine.table_names() method is deprecated and will be removed in a future release.  Please refer to Inspector.get_table_names(). (deprecated since: 1.4)
  engine.table_names()

['accounts', 'orders', 'region', 'sales_reps', 'web_events']

## Queries

### 1. Provide a table for all web_events associated with account name of Walmart. There should be three columns. Be sure to include the primary_poc, time of the event, and the channel for each event. Additionally, you might choose to add a fourth column to assure only Walmart events were chosen.

In [9]:
%%sql

SELECT a.primary_poc, w.channel, w.occurred_at, a.name
FROM web_events w
JOIN accounts a
ON w.account_id = a.id
WHERE a.name = 'Walmart';

 * postgresql://jovyan:***@localhost:8765/rsm-docker
39 rows affected.

[('Tamara Tuma', 'direct', '2015-10-06T17:13:58.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2015-11-05T03:08:26.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2015-12-04T03:57:24.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-01-02T00:55:03.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-02-01T19:02:33.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-03-02T15:15:22.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-04-01T10:58:55.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-05-01T15:26:44.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-05-31T20:53:47.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-06-30T12:09:45.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-07-30T03:06:26.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-08-28T06:42:42.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-09-26T23:14:59.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-10-26T20:21:09.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-11-25T22:52:29.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-12-24T05:35:14.000Z', 'Walmart'),
 ('Tamara Tuma', 'facebook', '2015-10-06T04:22:11.000Z', 'Walmart'),
 ('Tamara Tuma', 'organic', '2015-10-22T05:02:47.000Z', 'Walmart'),
 ('Tamara Tuma', 'adwords', '2015-10-22T14:04:20.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2015-11-05T17:18:54.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2015-12-11T08:44:16.000Z', 'Walmart'),
 ('Tamara Tuma', 'adwords', '2016-01-01T15:45:54.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-01-13T19:31:14.000Z', 'Walmart'),
 ('Tamara Tuma', 'adwords', '2016-02-07T17:44:10.000Z', 'Walmart'),
 ('Tamara Tuma', 'organic', '2016-02-27T15:27:22.000Z', 'Walmart'),
 ('Tamara Tuma', 'twitter', '2016-03-17T19:54:58.000Z', 'Walmart'),
 ('Tamara Tuma', 'organic', '2016-04-05T03:02:52.000Z', 'Walmart'),
 ('Tamara Tuma', 'organic', '2016-04-17T16:41:02.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-05-01T14:26:40.000Z', 'Walmart'),
 ('Tamara Tuma', 'banner', '2016-05-07T02:28:31.000Z', 'Walmart'),
 ('Tamara Tuma', 'organic', '2016-05-21T16:22:01.000Z', 'Walmart'),
 ('Tamara Tuma', 'facebook', '2016-06-02T04:41:31.000Z', 'Walmart'),
 ('Tamara Tuma', 'adwords', '2016-06-22T13:48:53.000Z', 'Walmart'),
 ('Tamara Tuma', 'banner', '2016-07-12T22:43:02.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-07-26T11:29:09.000Z', 'Walmart'),
 ('Tamara Tuma', 'banner', '2016-07-26T21:08:52.000Z', 'Walmart'),
 ('Tamara Tuma', 'organic', '2016-08-12T09:31:22.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-09-01T18:33:56.000Z', 'Walmart'),
 ('Tamara Tuma', 'adwords', '2016-09-11T17:06:53.000Z', 'Walmart')]

#### Cross Join with Proper WHERE clauses

In [17]:
%%sql

SELECT a.primary_poc, w.channel, w.occurred_at, a.name
FROM web_events w, accounts a
WHERE w.account_id = a.id 
AND a.name = 'Walmart';

 * postgresql://jovyan:***@localhost:8765/rsm-docker
39 rows affected.

[('Tamara Tuma', 'direct', '2015-10-06T17:13:58.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2015-11-05T03:08:26.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2015-12-04T03:57:24.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-01-02T00:55:03.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-02-01T19:02:33.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-03-02T15:15:22.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-04-01T10:58:55.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-05-01T15:26:44.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-05-31T20:53:47.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-06-30T12:09:45.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-07-30T03:06:26.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-08-28T06:42:42.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-09-26T23:14:59.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-10-26T20:21:09.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-11-25T22:52:29.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-12-24T05:35:14.000Z', 'Walmart'),
 ('Tamara Tuma', 'facebook', '2015-10-06T04:22:11.000Z', 'Walmart'),
 ('Tamara Tuma', 'organic', '2015-10-22T05:02:47.000Z', 'Walmart'),
 ('Tamara Tuma', 'adwords', '2015-10-22T14:04:20.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2015-11-05T17:18:54.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2015-12-11T08:44:16.000Z', 'Walmart'),
 ('Tamara Tuma', 'adwords', '2016-01-01T15:45:54.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-01-13T19:31:14.000Z', 'Walmart'),
 ('Tamara Tuma', 'adwords', '2016-02-07T17:44:10.000Z', 'Walmart'),
 ('Tamara Tuma', 'organic', '2016-02-27T15:27:22.000Z', 'Walmart'),
 ('Tamara Tuma', 'twitter', '2016-03-17T19:54:58.000Z', 'Walmart'),
 ('Tamara Tuma', 'organic', '2016-04-05T03:02:52.000Z', 'Walmart'),
 ('Tamara Tuma', 'organic', '2016-04-17T16:41:02.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-05-01T14:26:40.000Z', 'Walmart'),
 ('Tamara Tuma', 'banner', '2016-05-07T02:28:31.000Z', 'Walmart'),
 ('Tamara Tuma', 'organic', '2016-05-21T16:22:01.000Z', 'Walmart'),
 ('Tamara Tuma', 'facebook', '2016-06-02T04:41:31.000Z', 'Walmart'),
 ('Tamara Tuma', 'adwords', '2016-06-22T13:48:53.000Z', 'Walmart'),
 ('Tamara Tuma', 'banner', '2016-07-12T22:43:02.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-07-26T11:29:09.000Z', 'Walmart'),
 ('Tamara Tuma', 'banner', '2016-07-26T21:08:52.000Z', 'Walmart'),
 ('Tamara Tuma', 'organic', '2016-08-12T09:31:22.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-09-01T18:33:56.000Z', 'Walmart'),
 ('Tamara Tuma', 'adwords', '2016-09-11T17:06:53.000Z', 'Walmart')]

##### OR

In [18]:
%%sql

SELECT a.primary_poc, w.channel, w.occurred_at, a.name
FROM web_events w
CROSS JOIN accounts a
WHERE w.account_id = a.id 
AND a.name = 'Walmart';

 * postgresql://jovyan:***@localhost:8765/rsm-docker
39 rows affected.

[('Tamara Tuma', 'direct', '2015-10-06T17:13:58.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2015-11-05T03:08:26.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2015-12-04T03:57:24.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-01-02T00:55:03.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-02-01T19:02:33.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-03-02T15:15:22.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-04-01T10:58:55.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-05-01T15:26:44.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-05-31T20:53:47.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-06-30T12:09:45.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-07-30T03:06:26.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-08-28T06:42:42.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-09-26T23:14:59.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-10-26T20:21:09.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-11-25T22:52:29.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-12-24T05:35:14.000Z', 'Walmart'),
 ('Tamara Tuma', 'facebook', '2015-10-06T04:22:11.000Z', 'Walmart'),
 ('Tamara Tuma', 'organic', '2015-10-22T05:02:47.000Z', 'Walmart'),
 ('Tamara Tuma', 'adwords', '2015-10-22T14:04:20.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2015-11-05T17:18:54.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2015-12-11T08:44:16.000Z', 'Walmart'),
 ('Tamara Tuma', 'adwords', '2016-01-01T15:45:54.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-01-13T19:31:14.000Z', 'Walmart'),
 ('Tamara Tuma', 'adwords', '2016-02-07T17:44:10.000Z', 'Walmart'),
 ('Tamara Tuma', 'organic', '2016-02-27T15:27:22.000Z', 'Walmart'),
 ('Tamara Tuma', 'twitter', '2016-03-17T19:54:58.000Z', 'Walmart'),
 ('Tamara Tuma', 'organic', '2016-04-05T03:02:52.000Z', 'Walmart'),
 ('Tamara Tuma', 'organic', '2016-04-17T16:41:02.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-05-01T14:26:40.000Z', 'Walmart'),
 ('Tamara Tuma', 'banner', '2016-05-07T02:28:31.000Z', 'Walmart'),
 ('Tamara Tuma', 'organic', '2016-05-21T16:22:01.000Z', 'Walmart'),
 ('Tamara Tuma', 'facebook', '2016-06-02T04:41:31.000Z', 'Walmart'),
 ('Tamara Tuma', 'adwords', '2016-06-22T13:48:53.000Z', 'Walmart'),
 ('Tamara Tuma', 'banner', '2016-07-12T22:43:02.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-07-26T11:29:09.000Z', 'Walmart'),
 ('Tamara Tuma', 'banner', '2016-07-26T21:08:52.000Z', 'Walmart'),
 ('Tamara Tuma', 'organic', '2016-08-12T09:31:22.000Z', 'Walmart'),
 ('Tamara Tuma', 'direct', '2016-09-01T18:33:56.000Z', 'Walmart'),
 ('Tamara Tuma', 'adwords', '2016-09-11T17:06:53.000Z', 'Walmart')]

#### Example of Cross Join Expernsive Operation

In [ ]:
# %%sql
# --expensive statement
# SELECT a.primary_poc, w.channel, w.occurred_at, a.name
# FROM web_events w, accounts a

* When alias is used, the table name or column name has to be replaced with the alias everywhere within the query

### 2. Provide a table that provides the region for each sales_rep along with their associated accounts. Your final table should include three columns: the region name, the sales rep name, and the account name. Sort the accounts alphabetically (A-Z) according to account name.

In [27]:
# Limited to 100 rows to avoid scrolling, total 351 row

In [28]:
%%sql

SELECT s.name rep_name, a.name acc_name, r.name region
FROM sales_reps s
JOIN accounts a
ON s.id = a.sales_rep_id
JOIN region r
ON s.region_id = r.id
ORDER BY a.name
LIMIT 100;

 * postgresql://jovyan:***@localhost:8765/rsm-docker
100 rows affected.

[('Sibyl Lauria', '3M', 'Northeast'),
 ('Chau Rowles', 'Abbott Laboratories', 'Midwest'),
 ('Julie Starr', 'AbbVie', 'Midwest'),
 ('Earlie Schleusner', 'ADP', 'Southeast'),
 ('Marquetta Laycock', 'Advance Auto Parts', 'West'),
 ('Moon Torian', 'AECOM', 'Southeast'),
 ('Calvin Ollison', 'AES', 'Southeast'),
 ('Renetta Carew', 'Aetna', 'Northeast'),
 ('Cliff Meints', 'Aflac', 'Midwest'),
 ('Elba Felder', 'AIG', 'Northeast'),
 ('Georgianna Chisholm', 'Air Products & Chemicals', 'West'),
 ('Chau Rowles', 'Alcoa', 'Midwest'),
 ('Julia Behrman', 'Allstate', 'Northeast'),
 ('Georgianna Chisholm', 'Ally Financial', 'West'),
 ('Tia Amato', 'Alphabet', 'Northeast'),
 ('Charles Bidwell', 'Altria Group', 'Midwest'),
 ('Nakesha Renn', 'Amazon.com', 'Northeast'),
 ('Samuel Racine', 'American Airlines Group', 'Northeast'),
 ('Earlie Schleusner', 'American Electric Power', 'Southeast'),
 ('Julia Behrman', 'American Express', 'Northeast'),
 ('Hilma Busick', 'American Family Insurance Group', 'West'),
 ('Vernita Plump', 'Ameriprise Financial', 'Southeast'),
 ('Ayesha Monica', 'AmerisourceBergen', 'Northeast'),
 ('Delilah Krum', 'Amgen', 'Midwest'),
 ('Georgianna Chisholm', 'Anadarko Petroleum', 'West'),
 ('Ayesha Monica', 'Anthem', 'Northeast'),
 ('Michel Averette', 'Apple', 'Northeast'),
 ('Arica Stoltzfus', 'Applied Materials', 'West'),
 ('Vernita Plump', 'Aramark', 'Southeast'),
 ('Gianna Dossey', 'Archer Daniels Midland', 'Northeast'),
 ('Charles Bidwell', 'Arrow Electronics', 'Midwest'),
 ('Arica Stoltzfus', 'Assurant', 'West'),
 ('Necole Victory', 'AT&T', 'Northeast'),
 ('Dawna Agnew', 'Autoliv', 'West'),
 ('Delilah Krum', 'AutoNation', 'Midwest'),
 ('Dawna Agnew', 'AutoZone', 'West'),
 ('Arica Stoltzfus', 'Avis Budget Group', 'West'),
 ('Elna Condello', 'Avnet', 'Northeast'),
 ('Maren Musto', 'Baker Hughes', 'Southeast'),
 ('Dawna Agnew', 'Ball', 'West'),
 ('Cara Clarke', 'Bank of America Corp.', 'Northeast'),
 ('Vernita Plump', 'Bank of New York Mellon Corp.', 'Southeast'),
 ('Elwood Shutt', 'Baxter International', 'West'),
 ('Marquetta Laycock', 'BB&T Corp.', 'West'),
 ('Georgianna Chisholm', 'Becton Dickinson', 'West'),
 ('Calvin Ollison', 'Bed Bath & Beyond', 'Southeast'),
 ('Renetta Carew', 'Berkshire Hathaway', 'Northeast'),
 ('Eugena Esser', 'Best Buy', 'Northeast'),
 ('Marquetta Laycock', 'Biogen', 'West'),
 ('Moon Torian', 'BlackRock', 'Southeast'),
 ('Michel Averette', 'Boeing', 'Northeast'),
 ('Georgianna Chisholm', 'BorgWarner', 'West'),
 ('Maren Musto', 'Bristol-Myers Squibb', 'Southeast'),
 ('Elwood Shutt', 'Broadcom', 'West'),
 ('Micha Woodford', 'Cameron International', 'West'),
 ('Marquetta Laycock', 'Campbell Soup', 'West'),
 ('Delilah Krum', 'Capital One Financial', 'Midwest'),
 ('Debroah Wardle', 'Cardinal Health', 'Northeast'),
 ('Saran Ram', 'CarMax', 'Southeast'),
 ('Silvana Virden', 'Caterpillar', 'Northeast'),
 ('Micha Woodford', 'CBRE Group', 'West'),
 ('Babette Soukup', 'CBS', 'Southeast'),
 ('Calvin Ollison', 'CDW', 'Southeast'),
 ('Arica Stoltzfus', 'Celgene', 'West'),
 ('Cordell Rieder', 'Centene', 'Midwest'),
 ('Vernita Plump', 'CenturyLink', 'Southeast'),
 ('Brandie Riva', 'Charter Communications', 'West'),
 ('Babette Soukup', 'Chesapeake Energy', 'Southeast'),
 ('Julia Behrman', 'Chevron', 'Northeast'),
 ('Maren Musto', 'C.H. Robinson Worldwide', 'Southeast'),
 ('Tia Amato', 'CHS', 'Northeast'),
 ('Julia Behrman', 'Cigna', 'Northeast'),
 ('Ayesha Monica', 'Cisco Systems', 'Northeast'),
 ('Shawanda Selke', 'Citigroup', 'Northeast'),
 ('Gianna Dossey', 'Coca-Cola', 'Northeast'),
 ('Dorotha Seawell', 'Cognizant Technology Solutions', 'Southeast'),
 ('Nelle Meaux', 'Colgate-Palmolive', 'Southeast'),
 ('Akilah Drinkard', 'Comcast', 'Northeast'),
 ('Sherlene Wetherington', 'Community Health Systems', 'Midwest'),
 ('Calvin Ollison', 'Computer Sciences', 'Southeast'),
 ('Moon Torian', 'ConAgra Foods', 'Southeast'),
 ('Necole Victory', 'ConocoPhillips', 'Northeast'),
 ('Saran Ram', 'Consolidated Edison', 'Southeast'),
 ('Maryanna Fiorentino', 'Core-Mark Holding', 'West'),
 ('Marquetta Laycock', 'Corning', 'West'),
 ('Tia Amato', 'Costco', 'Northeast'),
 ('Hilma Busick', 'Crown Holdings', 'West'),
 ('Micha Woodford', 'CST Brands', 'West'),
 ('Saran Ram', 'CSX', 'Southeast'),
 ('Delilah Krum', 'Cummins', 'Midwest'),
 ('Elba Felder', 'CVS Health', 'Northeast'),
 ('Carletta Kosinski', 'Danaher', 'Midwest'),
 ('Calvin Ollison', 'DaVita HealthCare Partners', 'Southeast'),
 ('Brandie Riva', 'Dean Foods', 'West'),
 ('Elba Felder', 'Deere', 'Northeast'),
 ('Eugena Esser', 'Delta Air Lines', 'Northeast'),
 ('Moon Torian', 'Devon Energy', 'Southeast'),
 ('Marquetta Laycock', 'Discover Financial Services', 'West'),
 ('Dorotha Seawell', 'DISH Network', 'Southeast'),
 ('Ernestine Pickron', 'Disney', 'Northeast')]

### 3. Provide the name for each region for every order, as well as the account name and the unit price they paid (total_amt_usd/total) for the order. Your final table should have 3 columns: region name, account name, and unit price. A few accounts have 0 for total, so I divided by (total + 0.01) to assure not dividing by zero.

In [29]:
# Limited to 100 rows to avoid scrolling, total 6912 row

In [30]:
%%sql

SELECT (o.total_amt_usd/(o.total + 0.01)) unit_price, a.name acc_name, r.name region
FROM orders o
JOIN accounts a
ON a.id = o.account_id
JOIN sales_reps s
ON s.id = a.sales_rep_id
JOIN region r
ON s.region_id = r.id
LIMIT 100;

 * postgresql://jovyan:***@localhost:8765/rsm-docker
100 rows affected.

[(5.75960002366724, 'Walmart', 'Northeast'),
 (5.96517482031874, 'Walmart', 'Northeast'),
 (5.87970608287251, 'Walmart', 'Northeast'),
 (5.44423612294756, 'Walmart', 'Northeast'),
 (5.96018423125871, 'Walmart', 'Northeast'),
 (6.16871857118086, 'Walmart', 'Northeast'),
 (6.62891022521127, 'Walmart', 'Northeast'),
 (7.00385652366813, 'Walmart', 'Northeast'),
 (5.83342376559957, 'Walmart', 'Northeast'),
 (5.93581514762516, 'Walmart', 'Northeast'),
 (5.64652215166776, 'Walmart', 'Northeast'),
 (6.03341666241518, 'Walmart', 'Northeast'),
 (6.01949243718752, 'Walmart', 'Northeast'),
 (6.78065371926125, 'Walmart', 'Northeast'),
 (6.10980429503357, 'Walmart', 'Northeast'),
 (6.39113787591539, 'Walmart', 'Northeast'),
 (6.62915496476181, 'Walmart', 'Northeast'),
 (6.68556251374104, 'Walmart', 'Northeast'),
 (6.56982512579982, 'Walmart', 'Northeast'),
 (6.67046351200381, 'Walmart', 'Northeast'),
 (6.63571816589009, 'Walmart', 'Northeast'),
 (6.58486515497115, 'Walmart', 'Northeast'),
 (6.62800934601797, 'Walmart', 'Northeast'),
 (6.59953388284525, 'Walmart', 'Northeast'),
 (6.69379891923329, 'Walmart', 'Northeast'),
 (6.59988728405142, 'Walmart', 'Northeast'),
 (6.65467219990943, 'Walmart', 'Northeast'),
 (6.57626077791886, 'Walmart', 'Northeast'),
 (5.4544226873734, 'Express Scripts Holding', 'Northeast'),
 (5.2414506865689, 'Express Scripts Holding', 'Northeast'),
 (7.55677483648526, 'Express Scripts Holding', 'Northeast'),
 (7.45566316766224, 'Express Scripts Holding', 'Northeast'),
 (5.51108597958394, 'Freddie Mac', 'Northeast'),
 (6.01705850995386, 'Freddie Mac', 'Northeast'),
 (5.1458521541385, 'Freddie Mac', 'Northeast'),
 (5.35256353362327, 'Freddie Mac', 'Northeast'),
 (5.43916832873419, 'Freddie Mac', 'Northeast'),
 (5.49846471563273, 'Freddie Mac', 'Northeast'),
 (5.68641223487077, 'Freddie Mac', 'Northeast'),
 (5.23442297763648, 'Freddie Mac', 'Northeast'),
 (4.98981986209884, 'Freddie Mac', 'Northeast'),
 (5.58102663690908, 'Freddie Mac', 'Northeast'),
 (5.30672200254894, 'Freddie Mac', 'Northeast'),
 (5.59487581416718, 'Freddie Mac', 'Northeast'),
 (5.54291428410467, 'Freddie Mac', 'Northeast'),
 (5.38503231790383, 'Freddie Mac', 'Northeast'),
 (5.35388029163425, 'Freddie Mac', 'Northeast'),
 (5.29896179524132, 'Freddie Mac', 'Northeast'),
 (5.55668637851831, 'Freddie Mac', 'Northeast'),
 (5.34614102602951, 'Freddie Mac', 'Northeast'),
 (5.36785276772742, 'Freddie Mac', 'Northeast'),
 (5.42053937908047, 'Freddie Mac', 'Northeast'),
 (5.68665236225254, 'Freddie Mac', 'Northeast'),
 (4.9898302778817, 'Freddie Mac', 'Northeast'),
 (7.48882987033276, 'Freddie Mac', 'Northeast'),
 (5.21552857710773, 'Freddie Mac', 'Northeast'),
 (5.51509317932676, 'Freddie Mac', 'Northeast'),
 (5.69688274422851, 'Freddie Mac', 'Northeast'),
 (5.25893154752886, 'Freddie Mac', 'Northeast'),
 (5.43716697890562, 'Freddie Mac', 'Northeast'),
 (5.41595274991959, 'Freddie Mac', 'Northeast'),
 (5.28392338516966, 'Freddie Mac', 'Northeast'),
 (5.57860054870388, 'Freddie Mac', 'Northeast'),
 (5.59389517335503, 'Freddie Mac', 'Northeast'),
 (5.33650037395086, 'Freddie Mac', 'Northeast'),
 (5.00644496860569, 'Freddie Mac', 'Northeast'),
 (5.43027499209793, 'Freddie Mac', 'Northeast'),
 (5.34287776088245, 'Freddie Mac', 'Northeast'),
 (5.16206219229101, 'Freddie Mac', 'Northeast'),
 (7.61755882459247, 'Freddie Mac', 'Northeast'),
 (7.58185833114038, 'Freddie Mac', 'Northeast'),
 (7.56102428390148, 'Freddie Mac', 'Northeast'),
 (7.63443017064645, 'Freddie Mac', 'Northeast'),
 (7.68354744217225, 'Freddie Mac', 'Northeast'),
 (7.70995200579553, 'Freddie Mac', 'Northeast'),
 (7.45984363140323, 'Freddie Mac', 'Northeast'),
 (7.75136482191318, 'Freddie Mac', 'Northeast'),
 (7.60569101613825, 'Freddie Mac', 'Northeast'),
 (7.43839406458977, 'Freddie Mac', 'Northeast'),
 (7.27100037809155, 'Freddie Mac', 'Northeast'),
 (7.48584091491186, 'Freddie Mac', 'Northeast'),
 (7.69662562213665, 'Freddie Mac', 'Northeast'),
 (7.24139427096009, 'Freddie Mac', 'Northeast'),
 (7.5315741442912, 'Freddie Mac', 'Northeast'),
 (7.44204251083133, 'Freddie Mac', 'Northeast'),
 (7.5484674695009, 'Freddie Mac', 'Northeast'),
 (7.57920075246593, 'Freddie Mac', 'Northeast'),
 (7.4423057828967, 'Freddie Mac', 'Northeast'),
 (7.70535724814566, 'Freddie Mac', 'Northeast'),
 (7.61448161596221, 'Freddie Mac', 'Northeast'),
 (7.52774657102999, 'Freddie Mac', 'Northeast'),
 (7.39435528142862, 'Freddie Mac', 'Northeast'),
 (7.40068510925417, 'Freddie Mac', 'Northeast'),
 (7.50309058154712, 'Freddie Mac', 'Northeast'),
 (6.84309661466856, 'Ingram Micro', 'Northeast'),
 (6.00013985036012, 'Ingram Micro', 'Northeast'),
 (5.85966714608589, 'Ingram Micro', 'Northeast'),
 (6.11129829900549, 'Ingram Micro', 'Northeast'),
 (5.99906672888474, 'Ingram Micro', 'Northeast'),
 (5.8528882814186, 'Ingram Micro', 'Northeast')]

* 3 tables are joined one by one